function y = preprocessAlpha(x)
%  Preprocess input x
%    This function expects an input vector x and a vector of time values
%    tx. tx is a numeric vector in units of seconds.

% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 20-Nov-2020 21:18:00

Fs = 250; % Average sample rate
y = bandpass(x,[7 13],Fs,'Steepness',0.9999,'StopbandAttenuation',60);
y = bandpass(y,[7 13],Fs,'Steepness',0.9999,'StopbandAttenuation',50);
